### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/drupal-docker#1]
### \- Create new examples of **docker-compose.yml** such as:
- [ ] Nginx + php7 + MySQL
- [ ] Nginx + php7 + Postgres
- [ ] Nginx Reverse Proxy

---
- [ ] Aegir (full install)

---
- [ ] composer (external image)
- [ ] Adminer (external)
- [ ] xdebug (as external image)
- [ ] Blackfire (external image)
- [ ] Solr (external image)
- [ ] PimpMyLog (external image)
- [ ] grunt (with NodeJS)
- [ ] gulp (with Ruby)

---
- [ ] Install custom installation (eg Commerce Kickstart)
- [ ] Create Drupal project using composer

---
